### ISSUE TITLE
Error starting demo app

### ISSUE THREAD

**Issue by michaelkimball** [tinymce/tinymce-vue#297]
**What is the current behavior?**
On startup of the demo app, the server fails to run:
```
~/tinymce-vue$ yarn demo
yarn run v1.9.4
$ vite
 > src/demo/demo.ts:10:24: error: Could not resolve "/views/Refreshable.vue"
    10 │ import Refreshable from '/views/Refreshable.vue';
       ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~

 > src/demo/demo.ts:11:19: error: Could not resolve "/views/Tagged.vue"
    11 │ import Tagged from '/views/Tagged.vue';
       ╵                    ~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 2 errors:
src/demo/demo.ts:10:24: error: Could not resolve "/views/Refreshable.vue"
src/demo/demo.ts:11:19: error: Could not resolve "/views/Tagged.vue"
    at failureErrorWithLog (/home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:1493:15)
    at /home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:1149:7)
    at /home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:1258:14
    at /home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/mdak/test/tinymce-vue/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
error Command failed with exit code 1.
```
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**

1. `git clone https://github.com/tinymce/tinymce-vue.git`
2. `cd tinymce-vue/`
3. `yarn install`
4. `yarn demo`

**What is the expected behavior?**
The server starts up with the TinyMCE demo app at `localhost:3001`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**
Firefox 97.0.1 (64-bit)
Windows 10 Pro 64-bit (10.0, Build 19044)
This is my first time trying so I don't know if this worked on previous versions.

I was able to get it to run by commenting out line 39-48 of `src/demo/demo.ts`
```js
  // {
  //   path: '/refreshable',
  //   name: 'Refreshable',
  //   component: Refreshable
  // },
  // {
  //   path: '/tagged',
  //   name: 'Tagged',
  //   component: Tagged
  // }
```

**Comment by jscasca** [comment]
@michaelkimball Thanks for bringing that up! I just committed the missing pages.

**Comment by michaelkimball** [comment]
@jscasca Great, thanks! It works as expected now.
