### ISSUE TITLE
Build failed: Failed to resolve entry for package @tinymce/tinymce-vue

### ISSUE THREAD

**Issue by frederic117** [tinymce/tinymce-vue#417]
I'm experiencing an issue when building my Nuxt project due to a problem with the @tinymce/tinymce-vue package. The build process fails with the following error message: 
ERROR  Nuxt Build Error: [commonjs--resolver] Failed to resolve entry for package "@tinymce/tinymce-vue". The package may have incorrect main/module/exports specified in its package.json.
  at packageEntryFailure (/path/to/project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49436:17)
  at resolvePackageEntry (/path/to/project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49433:5)
  at tryNodeResolve (/path/to/project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49203:20)
  at Object.resolveId (/path/to/project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:48953:28)
  at /path/to/project/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
  at async PluginDriver.hookFirstAndGetPlugin (/path/to/project/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
  at async resolveId (/path/to/project/node_modules/rollup/dist/es/shared/node-entry.js:18355:26)
  at async ModuleLoader.resolveId (/path/to/project/node_modules/rollup/dist/es/shared/node-entry.js:18758:15)
  at async Object.resolveId (/path/to/project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:8258:10)
  at async PluginDriver.hookFirstAndGetPlugin (/path/to/project/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
Steps to Reproduce:

Install @tinymce/tinymce-vue in a Nuxt 3 project.
Attempt to build the project using npm run build.
Expected Behavior:
The build should complete successfully without errors.

Actual Behavior:
The build fails with an error indicating that the package entry for @tinymce/tinymce-vue could not be resolved.

Additional Information:

Nuxt Version: 3.11.2
@tinymce/tinymce-vue Version: 6.0.0
Temporary Workarounds Tried:

Reinstalling node modules.
Clearing Vite cache.
Manually specifying the package entry in the Vite configuration.
Ensuring all dependencies are up to date.
None of these workarounds have resolved the issue.

Suggestions:
It appears there might be an issue with the main, module, or exports fields in the package.json of @tinymce/tinymce-vue. A review and correction of these entries might resolve the problem.

Thank you for your assistance in resolving this issue.

**Comment by bert-w** [comment]
The build seems empty, check https://www.npmjs.com/package/@tinymce/tinymce-vue?activeTab=code

**Comment by alihardan** [comment]
Workaround:

```
$ git clone https://github.com/tinymce/tinymce-vue
$ cd tinymce-vue
$ yarn install --ignore-engines
$ yarn run build
```

then copy the `lib` directory to your `project/node_modules/@tinymce/tinymce-vue`  😁

**Comment by ThomasBerneHCSE** [comment]
There is no code in the package when installed : https://codesandbox.io/p/devbox/5q6jv2?migrateFrom=fg73hj

**Comment by vaecebyZ** [comment]
I'm running into this issue as well。🤣🤣🤣🤣

**Comment by danoaky-tiny** [comment]
We've identified the issue and are working on a fix. Apologies for the inconvenience.

**Comment by danoaky-tiny** [comment]
Please use v6.0.1, this has the built _/lib_.
